# TensoFlow

1. nd-array
2. GPU Support
3. Backpropagation - Computational- graph
4. Tensors are Immutable

# Imports

In [1]:
import tensorflow as tf
# import numpy as np
# from tqdm.notebook import tqdm

# Getting familiar 

In [2]:
x = tf.constant([1,2,3], shape = (3,1), dtype = tf.float32)
ones = tf.ones((3,3))
eye = tf.eye(3)
eye

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [3]:
x =tf.random.normal((3,3), mean = 0, stddev = 1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.8717674 ,  0.54125434,  1.7090832 ],
       [-0.80594254, -0.65628415,  0.1817105 ],
       [-1.0308754 ,  0.39248526, -1.7284844 ]], dtype=float32)>

In [4]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [22]:
x = tf.constant([1,2,3], shape = (3,1), dtype=tf.float32)
y = tf.constant([4,5,6], shape = (3,1), dtype=tf.float32)

In [16]:
tf.tensordot(x,y, axes = 1).numpy()

32.0

In [23]:
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[32.]], dtype=float32)>

In [21]:
tf.transpose(x)
x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [24]:
x = tf.constant([[1,2,3],[4,5,6]])

In [34]:
x_r = tf.reshape(x, (6,-1))

In [35]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [37]:
type(x_r)

tensorflow.python.framework.ops.EagerTensor